### ISSUE TITLE
Should this move under the threadly org?

### ISSUE THREAD

**Issue by jentfoo** [threadly/python-threadly#3]
Should we move this project under the threadly organization?  I forgot where we left with it, and sadly don't have the python skills to really evaluate it much.

**Comment by lwahlmeier** [comment]
+1

**Comment by lwahlmeier** [comment]
it should be in a pretty good state.  It might be worth removing depricated APIs and releasing a 1.x version of it before we do that, but not required.  currently it is a stable beta imo, but could easily be put to stable release.
